#----------------------------------------------------------------------------------------------
#  Copyright (c) 2020 - present Alexander Voitenko
#  Licensed under the MIT License. See License.txt in the project root for license information.
#----------------------------------------------------------------------------------------------

name: Mac

on:
  push:
    branches:
      - master
      - dev

jobs:
  All:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          #- 'Debug'
          - 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: install gtest
      run: |
        pushd /tmp
        curl -LO https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar -xf release-*
        cd googletest-release-*
        mkdir build
        cd build/
        cmake -DBUILD_SHARED_LIBS=ON ..
        make -j $(sysctl hw.physicalcpu | sed 's/hw.physicalcpu: //') # TODO: replace this with some sort of variable
        make install
        popd
    - name: install boost
      run: |
        brew install boost
    - name: build with Make (bundled GTest)
      run: |
        mkdir -p build_make
        cd build_make
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} \
              -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
              -DTARM_IO_BUILD_TESTS=TRUE \
              ..
        make -j $(sysctl hw.physicalcpu | sed 's/hw.physicalcpu: //')
    - name: build with Xcode (external GTest)
      run: |
        mkdir -p build_xcode
        cd build_xcode
        cmake -G Xcode \
              -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl \
              -DTARM_IO_BUILD_TESTS=TRUE \
              -DTARM_IO_USE_EXTERNAL_GTEST=TRUE \
              ..
        cmake --build . --config ${{ matrix.config }} -j $(sysctl hw.physicalcpu | sed 's/hw.physicalcpu: //')
    - name: run tests
      run: |
        ulimit -a
        cd build_make
        ./tests/tests --gtest_filter=*:-Timer*
        #make RunTests
