name: Mac

on:
  push:
    branches: [ dev ]

jobs:
  All:
    runs-on: macos-latest
    strategy:
      matrix:
        config:
          #- 'Debug'
          - 'Release'

    steps:
    - uses: actions/checkout@v2
    - name: install gtest
      run: |
        pushd /tmp
        curl -LO https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar -xf release-*
        cd googletest-release-*
        mkdir build
        cd build/
        cmake -DBUILD_SHARED_LIBS=ON ..
        make -j $(sysctl hw.physicalcpu | sed 's/hw.physicalcpu: //')
        make install
        popd
    - name: install boost
      run: |
        brew install boost
    - name: build Make
      run: |
        mkdir -p build_make
        cd build_make
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DTARM_IO_BUILD_TESTS=TRUE ..
        make -j $(sysctl hw.physicalcpu | sed 's/hw.physicalcpu: //')
    - name: build Xcode
      run: |
        mkdir -p build_xcode
        cd build_xcode
        cmake -G Xcode -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DTARM_IO_BUILD_TESTS=TRUE ..
        cmake --build . --config ${{ matrix.config }}
    - name: run tests
      run: |
        ulimit -a
        cd build_make
        ./tests/tests --gtest_filter=*:-Timer*
        #make RunTests
