name: Thread Sanitizer

on:
  push:
    branches:
      - master
      - dev

jobs:
  ALL:
    env:
      IMAGE_PATH: tarmio/builders:${{ matrix.docker_image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type:
          - 'Debug'
        docker_image:
          - ubuntu20.04-gcc9.3.0-boost1.71-cmake3.16.3-gtest1.10.0-openssl1.1.1g

    steps:
    - uses: actions/checkout@v2
    - name: docker pull
      run: docker pull ${IMAGE_PATH}
    - name: build
      run: |
        ./scripts/execute_in_docker.bash ${IMAGE_PATH} "mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DIO_SANITIZER=thread -DTARM_IO_BUILD_TESTS=TRUE .. && make -j$(nproc)"
    - name: run tests
      run: |
        ./scripts/execute_in_docker.bash ${IMAGE_PATH} "cd build && make RunTests"
