name: Valgrind

on:
  push:
    branches: [ dev ]

jobs:
  ALL:
    env:
      IMAGE_PATH: tarmio/builders:${{ matrix.docker_image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type:
          - 'Debug'
          #- 'Release'
        docker_image:
          #- ubuntu14.04-gcc4.8.4-boost1.55-cmake3.10.3-gtest1.10.0-openssl1.1.1g-valgrind3.16.0
          - ubuntu20.04-gcc9.3.0-boost1.71-cmake3.16.3-gtest1.10.0-openssl1.1.1g-valgrind3.16.0

    steps:
    - uses: actions/checkout@v2
    - name: docker pull
      run: docker pull ${IMAGE_PATH}
    - name: build
      run: |
        ./scripts/execute_in_docker.bash ${IMAGE_PATH} "mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DTARM_IO_BUILD_TESTS=TRUE .. && make -j$(nproc)"
    - name: valgrind check
      run: |
        ./scripts/execute_in_docker.bash ${IMAGE_PATH} "cd build && valgrind --leak-check=full --error-exitcode=1 ./tests/tests"
